# estimation setup ~ {options}
est: 
  data: "Data_US_all.jld" # empirical data file, null for simulated pseudo-empirical data ~ {"Data_US_all.jld", null}

# model setup ~ {options}
mod:
  model: "reh_hom_alC" # model identifier, see fcn_parameters.jl and fcn_model.jl for details ~ {"brf_hom_all", "brf_hom_trN", "brf_hom_trK", "reh_hom_all", "reh_hom_alN", "reh_hom_alC"}
  cali: "jb2efb1" # calibration identifier, see fcn_parameters.jl for details and valid model-calibration combinations ~ {"jb2efb", "jb2efb1", "jb2efbtau02kap005", "van01sd"}
  cons: "ph0" # search constraints identifier, see fcn_parameters.jl for details ~ {"bas", "ph0"}

# optimization setup ~ {options}
opt:
  optimizer: "bbo" # optimization package, "opt" for Optim.jl, "bbo" for BlackBoxOptim.jl ~ {"opt", "bbo"}
  sim: 2000 # number of simulations, default 1000 for simulated pseudo-empirical data, 2000 for empirical data
  iter: 4000 # number of inner iterations, default 40 for Optim.jl, 4000 for BlackBoxOptim.jl

